### ISSUE TITLE
Request to upload models to GoogleDrive

### ISSUE THREAD

**Issue by yfsong0709** [kenziyuliu/MS-G3D#1]
I am a student of CASIA, thanks to your kindly sharing. Due to some well known reasons, I can not download the pretrained models from Dropbox. Could you please upload the pretrained models to other platforms (e.g. GoogleDrive) and share them? Thank you very much.

**Comment by kenziyuliu** [comment]
Hi there,

Thanks for your interest! I have uploaded the pretrained models to GoogleDrive: https://drive.google.com/open?id=1y3VbEnINtyriy82apiTZJtBV1a3cywa-
