### ISSUE TITLE
The accuracy is so high, so will this paper be the end of NTU-60? Or will there be any potential for promotion? 

### ISSUE THREAD

**Issue by desertfex** [kenziyuliu/MS-G3D#11]
What's the possible directions for the following research?  Thank you.

**Comment by ZZYuting** [comment]
I think the directions are how to light the model. It seems cost much time.

**Comment by desertfex** [comment]
@ZZYuting The number of layers has dropped to 3 comparing with the ST-GCN with 10 layers. I have no idea how to light the model without loss of accuracy.

**Comment by ZZYuting** [comment]
> @ZZYuting The number of layers has dropped to 3 comparing with the ST-GCN with 10 layers. I have no idea how to light the model without loss of accuracy.
Although it has dropped to 3 compared with the st-gcn, the flops i caculate the model still up to 20G+flops, you can read some paper in cvpr 2020

**Comment by kenziyuliu** [comment]
My personal opinions:
- It seems that the performance on NTU RGB+D 60 dataset is getting saturated (e.g. suggested by [this preprint](https://arxiv.org/pdf/2004.03259.pdf), section 4.1) even with model ensembles, which are used by most work on this topic now; I would suggest working on NTU RGB+D 120 and Kinetics Skeleton 400 for future work.
- One future direction is to look at how to make MS-G3D more efficient (as @ZZYuting has pointed out). Some components that slow down training include the spatial-temporal window graph/feature construction and the use of graph residual masks. Please also check our [supplementary material](https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Liu_Disentangling_and_Unifying_CVPR_2020_supplemental.pdf) where we discuss some future directions.

**Comment by desertfex** [comment]
@kenziyuliu  Thank you very much indeed.

**Comment by kenziyuliu** [comment]
I'll close this issue now but please feel free to add more comments to this thread.

**Comment by Lyndsey-Xing** [comment]
> > @ZZYuting The number of layers has dropped to 3 comparing with the ST-GCN with 10 layers. I have no idea how to light the model without loss of accuracy.
> > Although it has dropped to 3 compared with the st-gcn, the flops i caculate the model still up to 20G+flops, you can read some paper in cvpr 2020

Hello,  how do you calculate flops in this paper? Is there any way to reduce flops？
Thanks.

**Comment by ZZYuting** [comment]
> > > @ZZYuting The number of layers has dropped to 3 comparing with the ST-GCN with 10 layers. I have no idea how to light the model without loss of accuracy.
> > > Although it has dropped to 3 compared with the st-gcn, the flops i caculate the model still up to 20G+flops, you can read some paper in cvpr 2020
> 
> Hello, how do you calculate flops in this paper? Is there any way to reduce flops？
> Thanks.
I use the ptflops to calculate flops coarsely. In fact, you can calculate flops on your hand which is more precise. I think it's a good way to learn how to reduce flops if you know which parts is complex.

**Comment by desertfex** [comment]
@ZZYuting Could you please provide the codes calculating the flops? I know its may be only two or three codes, but I still get "error" from the compiler. Thank you.

**Comment by ZZYuting** [comment]
from ptflops import get_model_complexity_info 
flops, params = get_model_complexity_info(model, (3, 10, 25, 2), as_strings=True, print_per_layer_stat=True)
 print("%s |%s |%s" % ('MSG3D', flops, params))

**Comment by desertfex** [comment]
@ZZYuting  Thank you very much.
