### ISSUE TITLE
Some questions about table 2

### ISSUE THREAD

**Issue by liubl1217** [kenziyuliu/MS-G3D#15]
Why the total count of parameters is half less than the baseline by simply replacing TCN with proposed multi-scale TCN module. I assume the proposed TCN module should contain more parameters as there are multiple branches in it.

**Comment by ZZYuting** [comment]
hi, I'm not the author. I think this is because the multi-scale tcn using 3x1 conv and deliation. For baseline, the tcn such as ST-GCN usually use 7x1 conv in and multi blocks. Maybe that's why less than the baseline. Welcom to discuss~

**Comment by liubl1217** [comment]
The multi-scale contains more than three 3*1 conv operators. And I think baseline+multi-scale tcn only aims at showing the effectiveness of proposed tcn module, without any motivation to change the whole model architecture.

**Comment by ZZYuting** [comment]
I think multi-scale tcn is not main contribution in this paper. Table 2  is used for fair comparison with ms-g3d. Maybe you can compute the flops using ptflops tools.

**Comment by liubl1217** [comment]
Ah, I am just trying to figure out whether this paper works is because it adds a lot of parameters given the core idea with regard to the feature sampling is relatively simple and straight. The running speed is much slower (around 3x slower) compared to its baseline, so it’s really confusing to see it contains much less parameters in table 2.

**Comment by ZZYuting** [comment]
I agree it seems slow. I public some useful tools for realtime demo. May be it's useful for you~
code here: https://github.com/ZZYuting/GCN_ActionRecongtionTools.git

**Comment by liubl1217** [comment]
Thanks for your great work! I’ll have a look on that!

**Comment by kenziyuliu** [comment]
Hi @Meta-Star, 

Thanks for your interest!

> I assume the proposed TCN module should contain more parameters as there are multiple branches in it.

The param count reduction comes from the 1x1 bottleneck conv (I believe 6 to 1 channel reduction for each branch) and replacing the 9x1 temporal conv in the baseline ([2s-AGCN](https://github.com/lshiwjx/2s-AGCN)) dilated 3x1 convs in MS-TCN. So as a quick example, if you have 96 input and output channels, originally you would have 9 * 1 * 96 * 96 = 82944 params, but now you would have (1 * 1 * 96 * 16 + 3 * 1 * 16 * 16) * 6 = 13824 params (assuming 6 branches, each with 3x1 conv). The actual MS-TCN would have fewer params as it has less than six 3x1 convs (Figure 3 (c)). I hope this helps explain the concept.

> I think baseline+multi-scale tcn only aims at showing the effectiveness of proposed tcn module, without any motivation to change the whole model architecture.

Yes, as @ZZYuting has rightly pointed out, the introduction of MS-TCN is not the main contribution of this paper. The motivation for adding MS-TCN is simply that it results in fewer params + stronger performance, thereby creating a stronger baseline from 2s-AGCN.

> Ah, I am just trying to figure out whether this paper works is because it adds a lot of parameters given the core idea with regard to the feature sampling is relatively simple and straight.

I would argue that the main ideas being simple and straight is not necessarily a bad thing :). The effectiveness of the proposed modules are verified with ablations in Table 1 (verifying the effectiveness of disentangled aggregation over sparser/denser graphs) and Table 2 (verifying the effectiveness of G3D by incrementally building up stronger baselines). 

I do agree that one of the drawbacks of this model is its relatively slow running speed, which generally stems from:
- the use of large spatial-temporal windows
- the use of graph residual masks (`A_res`), which was adapted from previous work


I hope this helps; please feel free to comment below for further questions.

**Comment by woshizhangcheng** [comment]
> I agree it seems slow. I public some useful tools for realtime demo. May be it's useful for you~
> code here: https://github.com/ZZYuting/GCN_ActionRecongtionTools.git

404
