### ISSUE TITLE
About the flops of the model

### ISSUE THREAD

**Issue by xf1994** [kenziyuliu/MS-G3D#16]
Thanks for the code sharing. I have some problems about the flops of the model.

I calculated the FLOPS of MS-G3D (msg3d.py single model), and I got the flops is of around 24G. Is this the correct number?

I was confused of the FLOPS because of this [paper](https://arxiv.org/pdf/2007.14690.pdf). The authors claim the flops of MSG3D is around 8G but I got 24G. I am not sure whether I am correct or they are correct. 
![image](https://user-images.githubusercontent.com/17975922/89044386-788af700-d37c-11ea-9d5b-285211bf7c1f.png)

BTW, the way of my calculating flops is using thop like:

    from thop import profile
    import sys
    sys.path.append('..')

    model = Model(
        num_class=60,
        num_point=25,
        num_person=2,
        num_gcn_scales=13,
        num_g3d_scales=6,
        graph='graph.ntu_rgb_d.AdjMatrixGraph'
    )

    N, C, T, V, M = 1, 3, 300, 25, 2
    x = torch.randn(N,C,T,V,M)
    model.forward(x)
    flops, params = profile(model, inputs = (x,))
    #print(out.shape)
    print(flops)
    print(params)
    print('Model total # params:', count_params(model))

**Comment by kenziyuliu** [comment]
Hi @xf1994, thanks for the interest! :)

I haven't done a very precise calculation myself, but from both `thop` (which you used) and [`ptflops`](https://pypi.org/project/ptflops/), the full MS-G3D net seems to use about 24G **MACs**. I would suggest checking with the authors of the quoted paper and see how they did their calculations.

**Comment by xf1994** [comment]
> Hi @xf1994, thanks for the interest! :)
> 
> I haven't done a very precise calculation myself, but from both `thop` (which you used) and [`ptflops`](https://pypi.org/project/ptflops/), the full MS-G3D net seems to use about 24G **MACs**. I would suggest checking with the authors of the quoted paper and see how they did their calculations.

Hi, sorry to bother you again. Is 24G the FLOPs of single joint stream? When two streams are used, the FLOPs will be 48G?

**Comment by kenziyuliu** [comment]
Hi there, 

Yes, the previous calculation was done for a single stream, so if we follow the way how [ShiftGCN](https://openaccess.thecvf.com/content_CVPR_2020/papers/Cheng_Skeleton-Based_Action_Recognition_With_Shift_Graph_Convolutional_Network_CVPR_2020_paper.pdf) considers multi-stream ensembles, then  a 2-stream ensemble would be 48G.

**Comment by xf1994** [comment]
> Hi there,
> 
> Yes, the previous calculation was done for a single stream, so if we follow the way how [ShiftGCN](https://openaccess.thecvf.com/content_CVPR_2020/papers/Cheng_Skeleton-Based_Action_Recognition_With_Shift_Graph_Convolutional_Network_CVPR_2020_paper.pdf) considers multi-stream ensembles, then a 2-stream ensemble would be 48G.

Thanks for your kind reply.
