### ISSUE TITLE
Snapshots of actions

### ISSUE THREAD

**Issue by hulianyuyy** [kenziyuliu/MS-G3D#19]
Congratulations for your great work! I have viewed your supplementary material and wanna inquire how to visualize the skeleton data. Could you please release the code?  Thank you very much!

**Comment by kenziyuliu** [comment]
Hi there,

Thanks for your interest :). The code for generating the visualizations (in README.md and in Supplementary) is actually available at the repo root (`ntu_visualize.py`). Feel free to play with it and comment below for any questions!

**Comment by hulianyuyy** [comment]
Thanks for your kind reply and solid work again!
