### ISSUE TITLE
IndexError on ensemble.py

### ISSUE THREAD

**Issue by egrassl** [kenziyuliu/MS-G3D#21]
Hello,

I have trained the joint and bone model for NTU120 and now I want to ensemble their results, therefore I am running the following command:

`python ensemble.py --dataset ntu120/xsub --joint-dir work_dir/ntu120/xsub/msg3d_joint/  --bone-dir work_dir/ntu120/xsub/msg3d_bone/`

But I am having this error:

> Traceback (most recent call last):
> File "ensemble.py", line 44, in <module>
>    _, r11 = r1[i]
> IndexError: list index out of range

I have printed the length of those lists and I found that `r1` and `r2` have different length than `label`:

> label: 101838
> r1: 50919
> r2: 50919

Can you help solving this issue?

Ps: I am using a CentOS Linux

**Comment by kenziyuliu** [comment]
Hi there, thanks for your interest!

I think there are only 50,919 testing examples (joint data and their labels) for NTU 120 XSub, but you seem to have double that number for `label`. Without further context, I'm guessing that when you generated your joint and bone data separately, you also generated their labels separately, but note that the joint data and the bone data use the same set of 50919 labels.

Hope this helps and feel free to comment below for further questions.

**Comment by egrassl** [comment]
I am trying to solve this problem, but I cannot understand how it happened. I have followed your tutorial and ran the following commands:
- `python ntu120_gendata.py`
- `python gen_bone_data.py --dataset ntu120`

Can you give me a clue about how to solve this?
Will I have to train the Joint and Bone models again?

**Comment by kenziyuliu** [comment]
Hi there,

The data generation process goes like:
1. You first download raw skeleton data of NTU RGB+D 
    - For NTU 120, this includes 2 zips `nturgbd_skeletons_s001_to_s017.zip`, `nturgbd_skeletons_s018_to_s032.zip`
    - The first zip contains only NTU 60 data, and the second zip contains additional data for NTU 120 on top of NTU 60, and they are unzipped into different folders `nturgb+d_skeletons/`, `nturgb+d_skeletons120/`

2. You then run `python3 ntu120_gendata.py` to generate the training examples (input and output/label tensors) from the raw skeleton files (labels are part of the filenames)
    - Depending on the filename, each example gets assigned to "train" or "test"
    - `nturgb+d_skeletons/` and `nturgb+d_skeletons120/` gives you around 113,945 samples in total, and NTU 120 XSub splits them (depending on the filenames) into 63,026 training samples and 50,919 testing samples

So if you have 101838 **testing samples** for NTU 120 XSub, then there might be a mistake somewhere when you generated your labels.

As for whether you need to train the models again: I'd say it depends on what your training/testing data are like. I would suggest trying re-generating your data from the raw skeleton files by carefully following the steps in README first, and then see if you trained your model on the wrong data. 

The good news though seems to be that your `r1` and `r2` tensors seem to have the right number of samples (both joint and bone predict on 50919 testing samples).

**Comment by egrassl** [comment]
Thank you for your fast reply.

The reason why I've had 101838 testing samples was because I have extracted both NTU60 and NTU120 samples to the same `nturgb+d_skeletons120/` folder.

After realizing that, I deleted every sample in my databases folders and dowloaded NTU60 and NTU120 again. I have extracted both in different directories as the readme instructs, but now I have the following scenario for `ntu120/xsub`:

> Labels: 68864 
> r1: 34432
> r2: 34432

It is interesting because the labels are always twice the ammount of testing samples in `r1` and `r2`. I deleted everything and processed everything again, but I've got the same result. I also tried to read the `ntu120_gendata.py`, but I couldn't find any line where data could be doubled or halved.

Do you have any other suggestion to help me?

**Comment by kenziyuliu** [comment]
Hi @egrassl,

Without further context, I would guess that there might be just a very simple bug somewhere in your modified code :). I would suggest try cloning a new, separate MS-G3D repo and copy your raw data (the zip files) to there and follow the instructions closely to generate you data again and see if this is indeed the case.

**Comment by egrassl** [comment]
Thank you. I will do that and let you know the results!

Also, may I ask you one last question before I do that?

My directories structure is in the picture bellow. I have extracted the samples from the zip files into the two ntu directores as the readme instructs. Do you see any problem with my raw data structure for NTU120?

![Screenshot_20201020_205759](https://user-images.githubusercontent.com/10728842/96656775-f37a0300-1316-11eb-99f1-829555117b39.png)

**Comment by kenziyuliu** [comment]
> Thank you. I will do that and let you know the results!
> 
> Also, may I ask you one last question before I do that?
> 
> My directories structure is in the picture bellow. I have extracted the samples from the zip files into the two ntu directores as the readme instructs. Do you see any problem with my raw data structure for NTU120?
> 
> ![Screenshot_20201020_205759](https://user-images.githubusercontent.com/10728842/96656775-f37a0300-1316-11eb-99f1-829555117b39.png)

It does look good to me, though I'll just repeat that the content of `nturgbd_skeletons_s001_to_s017.zip` goes to `nturgb+d_skeletons/` and the content of `nturgbd_skeletons_s018_to_s032.zip` goes to `nturgb+d_skeletons120/` and you should be good.

**Comment by egrassl** [comment]
@kenziyuliu thank you very much and sorry for giving you trouble!

I did not rembember changing the `ntu120_gendata.py` file, but I probably did it by accident.

I have one more question, but I will make it a new topic since it is related to fine tuning.
