### ISSUE TITLE
failure to excute the file of main.py

### ISSUE THREAD

**Issue by a14en9** [kenziyuliu/MS-G3D#3]
Hi,

Great job!

Thank you for sharing the code. I was encountered the following error while executing the main.py file.

"CUDA out of memory. Tried to allocate 1.29 GiB (GPU 0; 10.76 GiB total capacity; 8.00 GiB already allocated; 789.94 MiB free; 625.17 MiB cached)"
 
My GPU is Nvidia 2080TI and I have tried to set a small batch size, but it seems not working for me. Can you give me some suggestions to solve it.

Thank you in advance.

**Comment by kaiser-hamid-rabbi** [comment]
You just need more GPU power to execute your command.
