### ISSUE TITLE
code for plotting Fig 2 in the paper

### ISSUE THREAD

**Issue by a14en9** [kenziyuliu/MS-G3D#30]
Would you like to share the script used to plot matrix powers in Figure 2 of this paper, please?

Thanks in advance!

**Comment by kenziyuliu** [comment]
Hi @cvhabitat,

Thanks for your interest :). I couldn't find the code for plotting the diagram and I probably just did it from IPython. A couple of pointers tho:
- Write the code for generating the matrices (e.g. https://github.com/kenziyuliu/MS-G3D/blob/master/model/ms_gcn.py#L27)
- Use `matplotlib.pyplot.matshow()` to plot the matrices
- Set the color theme (see https://matplotlib.org/tutorials/colors/colormaps.html). Forgot which one I used though.

Hope this helps!
