### ISSUE TITLE
required time for training on kinetics

### ISSUE THREAD

**Issue by parvanehabi** [kenziyuliu/MS-G3D#31]
hi
How long does it take to train model on kinetics dataset for a few examples of the different hardware you tested before?

**Comment by kenziyuliu** [comment]
Hi @parvanehabi, thanks for your interest! If I recall correctly it takes a _while_ to train on Kinetics. I was sharing the training log in another issue earlier, see [here](https://github.com/kenziyuliu/MS-G3D/issues/26#issuecomment-720198079). Seems like it takes 4 days to train on the whole dataset. I don't quite remember what hardware it was using, probably 1080Ti's. Hope this helps!
