### ISSUE TITLE
Some problems with motion recognition

### ISSUE THREAD

**Issue by melon-coder** [kenziyuliu/MS-G3D#33]
Hello, may I ask, when there are two people in the RGB video (such as when playing tennis), which person is predicted by the current video frame?and does this project have the function of motion recognition? Or is it just a feature extractor?

**Comment by kenziyuliu** [comment]
Hi @melon-coder,

Thanks for your interest! If I recall correctly (at least for NTU datasets), the input tensor to the network has shape (N=batch, C=channels=3, T=frames, V=nodes, M=num_persons=2), i.e. the number of skeletons is represented by the last axis; if there's only 1 person then the 2nd skeleton is set to zero.  See L154/L173 of `model/msg3d.py`. 

Hope this helps!
