### ISSUE TITLE
How to combine the two data training?(怎么把bone和joint两种数据一起训练呢)

### ISSUE THREAD

**Issue by ZuoLeo** [kenziyuliu/MS-G3D#4]
Hi, authors, your article is so nice! I have a question to ask you.Two types of data concat together initially C=6, and then as input in the network how to deal with it? According to 2s-agcn, you input the two kinds of data into the network respectively and then you feed them into the softmax classifier, and then you add up the output probabilities. or  choose to add the two outputs into loss respectively, or  add them into the (n,c) tensor of the network? How do you do that?
大佬你好，你的文章真的很精彩，我有一个问题想问你。两种数据concat到一起初始C=6，然后作为输入在网络中如何处理呢？按照2s-AGCN的说法是将两种数据的分别输入网络然后在送入softmax分类器，输出概率进行加和，是选择把两个输出分别送进loss进行相加吗，还是网络输出的（n,c）tensor进行相加呢，是怎么处理呢？

**Comment by kenziyuliu** [comment]
Hi there, thanks for your interest :)

Currently, "two-streams" are formulated as a model ensemble (i.e. train _two identical models_ with different data, and merge their softmax scores to get final predictions). 

If you want to try training a single model with both joint and bone data, then you should write a separate `Dataset` class (follow `feeder.py`) that loads and concatenates the preprocessed joint and bone data at the same time to give you a `N x C=6 x T x V x M` tensor. Though in general, I would expect the performance of model ensembles to better.
