### ISSUE TITLE
ST-private

### ISSUE THREAD

**Issue by satorutada** [kenziyuliu/MS-G3D#43]
https://github.com/kenziyuliu/MS-G3D/blob/88ef4ef990ec49547e1c083e9e93352e12841543/LICENSE#L140-L158

**Comment by kenziyuliu** [comment]
Hi @satorutada, what can I do for you?

**Comment by satorutada** [comment]
Hi @kenziyuliu, thanks for your comment. This license says that it's not allowed to use MS-G3D for commercial purpose. Is my understanding correct?

**Comment by kenziyuliu** [comment]
I just updated the repo to MIT License :).

Re your question: The earlier license was https://creativecommons.org/licenses/by-nc/4.0/, which prohibits commercial use as you noted correctly.
