### ISSUE TITLE
Vs code运行代码直接终止，并且没有报错

### ISSUE THREAD

**Issue by MosasaurYi** [kenziyuliu/MS-G3D#45]
你好，请问我复现该代码的时候，使用VS code 和anaconda来跑，环境都没问题，在跑的时候，进入第一次训练，然后程序就直接终止了了，也没有任何的报错，请问这怎么解决呢？

**Comment by Anirudh257** [comment]
@MosasaurYi Can you post the screenshot of your error? I was able to run successfully using the python virtualenvironment.

**Comment by MosasaurYi** [comment]
here,it stop&nbsp;directly without any error
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kenziyuliu/MS-G3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kenziyuliu/MS-G3D] Vs code运行代码直接终止，并且没有报错 (#45)





 
@MosasaurYi Can you post the screenshot of your error? I was able to run successfully using the python virtualenvironment.

**Comment by MosasaurYi** [comment]
> @MosasaurYi Can you post the screenshot of your error? I was able to run successfully using the python virtualenvironment.

I find my code will stop in “loss.backward()”，and without error，do you know why，thanks

**Comment by Anirudh257** [comment]
Decrease your batch-size and see if your GPU memory is getting full.

**Comment by MosasaurYi** [comment]
> Decrease your batch-size and see if your GPU memory is getting full.

it is all ok,when i debug it,i find the tensor of loss was empty and the error “RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED”，is there any problem with the version of cuda and cudann,cuda9.2 and cudann 7.6.5for cuda92 in my computer,What version are you using?Thanks for reply

**Comment by Anirudh257** [comment]
I am using python3.5, cuda 10, cudnn 7 on ubuntu.

**Comment by kenziyuliu** [comment]
Hi there, sorry for the late reply. Have you resolved the issue? This looks like a problem relating to your local environment setup.
