### ISSUE TITLE
running_mean should contain 54 elements not 108

### ISSUE THREAD

**Issue by llgzr** [kenziyuliu/MS-G3D#47]
Hi, 

when I run the test on Kinetics-400 dataset I get this error: 

`running_mean should contain 54 elements not 108`

there are some solution to this issue? 

Thanks.

**Comment by kenziyuliu** [comment]
Hi there, sorry for the late reply. I haven't run into this issue before :/. Have you tried re-cloning the repo in case you changed your repo locally? If you clone the repo and evaluate the pre-trained models directly everything should work.

**Comment by MikuuGithub** [comment]
> Hi,
> 
> when I run the test on Kinetics-400 dataset I get this error:
> 
> `running_mean should contain 54 elements not 108`
> 
> there are some solution to this issue?
> 
> Thanks.

Maybe you could check the type of datasets and the method of pose estimation.
