### ISSUE TITLE
kinect 400 dataset

### ISSUE THREAD

**Issue by yanghhx** [kenziyuliu/MS-G3D#48]
Hello, I could not download kinect 400 dataset from ST-GCN .could you please send a link for me ? I badly need it for my research .My e-mail is qinyangz@163.com
 I'll be very grateful if you could send it to me.
 Thank you a lot.

**Comment by kenziyuliu** [comment]
Hi there, sorry for the late reply. Unfortunately I haven't kept a local copy due to disk space. The Google Drive link from https://github.com/yysijie/st-gcn/blob/master/OLD_README.md#kinetics-skeleton seems to work. Have you tried that?
