### ISSUE TITLE
kinetics normalization differs to ST-GCN, what's the meaning?

### ISSUE THREAD

**Issue by ZZYuting** [kenziyuliu/MS-G3D#5]
I have reproduce your paper. The result are good and I view the ST-GCN codes and find some differences.
In ST-GCN
     centralization
        data_numpy[0:2] = data_numpy[0:2] - 0.5
        data_numpy[0][data_numpy[2] == 0] = 0
        data_numpy[1][data_numpy[2] == 0] = 0
In MS-G3D your code is:
   centralization
        data_numpy[0:2] = data_numpy[0:2] - 0.5
        **data_numpy[1:2] = -data_numpy[1:2]**
        data_numpy[0][data_numpy[2] == 0] = 0
        data_numpy[1][data_numpy[2] == 0] = 0

why you turn data_numpy[1:2] to -data_numpy[1:2]? Is helpful for our model? I will do experiments according to ST-GCN later~

**Comment by kenziyuliu** [comment]
Hi there,

The normalization code for Kinetics Skeleton 400 has was based on 2s-AGCN (see https://github.com/lshiwjx/2s-AGCN/blob/master/data_gen/kinetics_gendata.py). I haven't really looked into it, but I would suggest contacting the original author :)

**Comment by ZZYuting** [comment]
> haven't really looked into it, but I would suggest contacting the original author :)
Answers:
The data in kinetics ranges from 0 to 1, "-0.5" makes it to -0.5-0.5.
The second row is the direction problem, for better visualization
