### ISSUE TITLE
Change number of people in model

### ISSUE THREAD

**Issue by tucachmo2202** [kenziyuliu/MS-G3D#51]
Hi, thanks for great works,

I see that in your implementation, you fixed 2 as number of skeleton so how to change it to be flexible with any people number?
Thank you very much!

**Comment by kenziyuliu** [comment]
Hi @tucachmo2202,

Thanks for your interest. If I recall correctly the model definition should be able to handle multiple persons (you can adjust the number of skeletons here: https://github.com/kenziyuliu/MS-G3D/blob/master/model/msg3d.py#L187). So for a dataset with multiple skeletons per frame, you can always retrain the model.

If your question was about having the model take a variable number of skeletons at different frames — I don't think it is currently supported. For datasets that may have video sequences with > 2 skeletons (e.g. Kinetics), I believe the workaround was simply to cap the number of skeletons at 2 following previous work (https://github.com/kenziyuliu/MS-G3D/blob/master/data_gen/kinetics_gendata.py#L53).

Hope this helps!

**Comment by tucachmo2202** [comment]
Hi @kenziyuliu, 

Thank for your supporting. I found the way to change the number of people it is fix the feature of batchnorm1D to in_channels * num_point: https://github.com/kenziyuliu/MS-G3D/blob/master/model/msg3d.py#L1119
