### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'ntu' when run python ntu_gendata.py

### ISSUE THREAD

**Issue by CyWang-Jade** [kenziyuliu/MS-G3D#52]
Did someone teach me how to solve this problem?

**Comment by kenziyuliu** [comment]
Hi @CyWang-Jade,

Thanks for your interest. You would get this error when you try to cast the string "ntu" to an integer. Looking at `https://github.com/kenziyuliu/MS-G3D/blob/master/data_gen/ntu_gendata.py` I would suggest ensuring the filenames for the NTU dataset are correct.

**Comment by CyWang-Jade** [comment]
> 

Thank you very much,  I forgot to remove the data package from the file.
