### ISSUE TITLE
How to make the frames not change?

### ISSUE THREAD

**Issue by LIUQI-creat** [kenziyuliu/MS-G3D#56]
Hi,
@kenziyuliu 
Thanks for your excellent work! The data shape I use is [4,2,900,17,1], which means its frames are 900, and its output's shape before average pooling is [4, 384, 225, 17].  Does it mean that the number of frames decreases after passing through the network？

I want to get **[4,384,900,17]**, so it will be [4, num_classes, 900, 1] after fc.
How should I write code to keep the frame number unchanged?

Looking forward to your reply ! Thank you again.

**Comment by kenziyuliu** [comment]
Hi @LIUQI-creat, thanks for your interest! It's been a while and I don't recall the details, but take a look at https://github.com/kenziyuliu/MS-G3D/blob/master/model/ms_tcn.py to see where you can adjust the temporal downsampling. Looks like this line that does stride=2 temporal convolutions (and other places with stride=2) is relevant: https://github.com/kenziyuliu/MS-G3D/blob/master/model/msg3d.py#L138. Hope this helps!

**Comment by LIUQI-creat** [comment]
> Hi @LIUQI-creat, thanks for your interest! It's been a while and I don't recall the details, but take a look at https://github.com/kenziyuliu/MS-G3D/blob/master/model/ms_tcn.py to see where you can adjust the temporal downsampling. Looks like this line that does stride=2 temporal convolutions (and other places with stride=2) is relevant: https://github.com/kenziyuliu/MS-G3D/blob/master/model/msg3d.py#L138. Hope this helps!

Thanks !!!  ^^
