### ISSUE TITLE
Can anybody provide kinetics_train_label.json and kinetics_val_label.json file? 急求，非常急的那种～～

### ISSUE THREAD

**Issue by xueyingliu** [kenziyuliu/MS-G3D#6]
Can anybody provide these two json file? 
I can't find them. Thanks so much.
> kinetics_train_label.json 
> kinetics_val_label.json

**Comment by kenziyuliu** [comment]
Hi there, 

The raw labels are available from the Kinetics Skeleton dataset (see [README.md](https://github.com/kenziyuliu/MS-G3D#kinetics-skeleton-400)) and I extracted them for you:

https://drive.google.com/file/d/1Yeiv1IMBY2KV2g1mn9gG-aWezhOf4oHe/view?usp=sharing
