### ISSUE TITLE
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 131072.0

### ISSUE THREAD

**Issue by wjm-wjm** [kenziyuliu/MS-G3D#9]
Hi, here
I train your model on the dataset of kinetics. I set '--amp_opt_level 2 --half', because if I do not do that, it will reply an error ' CUDA out of memory'(My GPU's version is RTX 2080Ti and I only use one GPU). However, it appears 'Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 131072.0' every a few of steps. Do you have this problem?
![2020-06-22 12-40-31屏幕截图](https://user-images.githubusercontent.com/53390698/85249355-1f2ece80-b486-11ea-8886-a403aa935763.png)

**Comment by kenziyuliu** [comment]
Hi there, 

This is the output of the [NVIDIA Apex package](https://github.com/NVIDIA/apex). As long as there are no NaNs then I think there should be nothing to worry about (see https://github.com/NVIDIA/apex/issues/318#issuecomment-493797866).

**Comment by wjm-wjm** [comment]
Ok, thanks a lot!
